### ISSUE TITLE
I am facing some weird issues on select component.

### ISSUE THREAD

**Issue by hardcommitoneself** [N00nDay/stwui#155] opened 2023-09-07 16:11 UTC
The following is what I have used the select component on my project.

```
<Select name="proof" placeholder="Basic" multiple bind:value={currentProofs}>
	<Select.Options slot="options">
		{#each proofOptions as option}
			<Select.Options.Option {option} selected="false" />
		{/each}
	</Select.Options>
</Select>
```

Once I have changed the `currentProofs`(in case that I want to edit one item of list), the selected items were not reflected on dropdown menu.
![image](https://github.com/N00nDay/stwui/assets/104041595/9d1b88e8-193d-4997-babd-50cbf6018536)

**Comment by N00nDay** [comment] 2023-09-10 15:52
Please provide a reproduction. I am not following what your issue is with the description laid out.

**Comment by N00nDay** [comment] 2023-09-22 16:19
Closing this issue as no reproduction has been provided and I cannot reproduce myself.

**Closed by N00nDay** 2023-09-22 16:19 UTC
